# Generated by Django 4.2.7 on 2024-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("games_count", models.PositiveIntegerField(default=0)),
                ("score_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
